### PR TITLE
414 home page resource linking

### LINKED ISSUE #414: Home Page Resource Linking
### Problem
Following #411, we now have unique URLSearchParams that enable scrolling to specific resources or categories. The format is as follows:
- For categories: `/Resources#<CategoryName_separated_by_dashes>` (ex: `/Resources/Food-Resources`)
- For resources: `/Resources#<ObjectId>` (ex: `/Resources#60a5a5661d9811d718c3d998` takes you to Food Pantry)

All that's left for the Home page is to combine these URLSearchParams with the results from the search bar. After this, we'll have a fully functional home page!

### Notes
- [ ] It'll likely be helpful to review Brian's PR. There is currently a bug where copy-pasting the URL for a specific resource doesn't scroll to the appropriate resource. I believe this is because the scrolling and page rendering happen concurrently, so it attempts to scroll to a resource that doesn't exist yet. Brian is currently working on a fix for this, and hopefully this only applies to manually setting URLs and not routing to them.
- [ ] Make sure to run `git pull` before any development work
- [ ] Complete your development in a new branch
- [ ] Link this issue to your PR
- [ ] Feel free to reach out if you have any questions!

### Task
- [x] Connect the URLSearchParams to Homge page search results
- [x] Selecting a resource from the search result should append the `ObjectId` to the URL
- [x] Selecting a resource should open the Resource page and scroll to that resource (but if this doesn't work until the bug fix comes out, that's fine just mention it in the PR)

### PR DESCRIPTION
**Pull request by Joelsp19**
closes #414

# Overall Notes
- Home page can now scroll to the individual resource (yay!)
- The resource is programmatically clicked on to be expanded, and then uses a custom scroll function to scroll to the resource with some offset (might have to work this out but I think we need this bc of the search bar blocking)
- The #(anchor) is used to represent what was clicked on last (either an id or a category-name-sep-by-dashes)
- Clicking on a home page icon updates the corresponding filter in the dropdown
- Clicking on a resource on the resource page updates the anchor which updates the url
- Experimented with HashLinks but overall opted for manually doing the scrolling on render/refresh so that we can solve the "paste" problem.

https://github.com/user-attachments/assets/a548e21d-aed1-4e7e-b1a2-23606dd2844f

### CODE REVIEW

File: frontend/src/pages/HomePage/HomePage.js [hunk 1]
```diff
@@ -70,10 +76,10 @@ function HomePage({ setActiveLink }) {
...
             id: 'Financial-Resources-and-Education',
         },
-        {
-            title: 'Counseling Services',
-            id: 'Counseling-and-Psychological-Services',
-        },
+        // {
+        //     title: 'Counseling Services',
+        //     id: 'Counseling-and-Psychological-Services',
+        // },
```
Comment (seanmnguyen) [inline frontend/src/pages/HomePage/HomePage.js:82]: Sorry about the mix up with the 4 vs 5 icons! Can you add "Health Services" that will map to the (believe it or not) "Health Services" category? We're also thinking of changing the icon for "Self Help" while we're at it.

- Self Help should have [this icon](https://www.flaticon.com/free-icon/affection_10133746?term=self+love&page=1&position=32&origin=search&related_id=10133746)
- Health Services should have [this icon](https://www.flaticon.com/free-icon/drugstore_4320337?term=pharmacy&page=1&position=5&origin=search&related_id=4320337)

Feel free to delete the icons we're not using anymore and rename the other ones, if their current names don't make sense. Thanks!
